version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/maven-archetype-webapp.war maven-archetype-webapp.war
artifacts:
  files:
    - maven-archetype-webapp.war
